import Vue from 'vue'
import VueRouter from 'vue-router'
import IndexView from '../views/indexView/index'
import SearchView from '../views/resultList/searchList'

Vue.use(VueRouter)

const routes = [
  {
    path:'/',
    name:'index',
    component:IndexView,
    meta:{
      isAuth:false
    }
  },
  {
    path:'/map',
    name:'gyg',
    component:()=>import('../views/strollMap/index.vue'),
    meta:{
      isAuth:false
    }
  },
  {
    path:'/postjob',
    name:'postjob',
    component:()=>import('../views/postJob/index'),
    meta:{
      isAuth:true
    }
  },
  {
    path:'/info',
    name:'message',
    component:()=>import('../views/getInfor/index'),
    meta:{
      isAuth:true
    }
  },
  {
    path:'/personal',
    name:'myinfo',
    component:()=>import('../views/personalCenter/index'),
    meta:{
      isAuth:true
    }
  },{
    path:'/tobezpf',
    name:'cwzpf',
    component:()=>import('../views/postJob/tobezp.vue'),
    meta:{
      isAuth:true
    }
  },
  {
    path:'/newmechanism',
    name:'mecha',
    component:()=>import('../views/postJob/newmecha.vue'),
    meta:{
      isAuth:true
    }
  },
  {
    path:'/search/:text',
    name:'search',
    component:SearchView
  },{
    path:'/shortterm',
    name:'shortTerm',
    component:()=>import('../views/resultList/shortTerm')
  },{
    path:'/longterm',
    name:'longTerm',
    component:()=>import('../views/resultList/longTerm')
  },{
    path:'/network',
    name:'network',
    component:()=>import('../views/resultList/network')
  },{
    path:'/vacation',
    name:'vacation',
    component:()=>import('../views/resultList/vacation')
  },
  {
    path:'/notice/:nid',
  name:'notice',
  component:()=>import('../views/notice/index')
},{
  path:'/job/:jid',
  name:'job',
  component:()=>import('../views/jobInfo/index')
},
{
  path:'/cv',
  name:'cv',
  component:()=>import('../views/personalCenter/cvManage'),
  meta:{
    isAuth:true
  }
},
{
  path:'/sphistory',
  name:'sphistory',
  component:()=>import('../views/spHistory/index'),
  meta:{
    isAuth:true
  }
},
{
  path:'/personalinfo',
name:'pinfo',
component:()=>import('../views/personalCenter/personalInfo'),
meta:{
  isAuth:true
}
}
,{
  path:'/company',
  name:'company',
  component:()=>import('../views/personalCenter/company'),
  meta:{
    isAuth:true
  }
}
]

const router = new VueRouter({
  //mode: 'history',
  base: process.env.BASE_URL,
  routes
})
router.beforeEach((to,from,next)=>{
  if(to.meta.isAuth){
   if(sessionStorage.getItem('user')){
    next()
   }else{
    window.alert("请先登录")
    next(false)
   }
  }else{
    next()
  }
})

export default router
